export const awards = [
  {
    name: "Independent of the year",
    type: "Nominee",
    project: "INNOVATE 2024",
    label: "Awwwards",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "LVXH - AMOT",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Open Field Audio",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "ArtisanCraft",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Disguised Edge",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Silvia Santiago",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "2023 Showcase",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Digital Excellence Awards",
    label: "Vacuum",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Harmonic Pitch",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Shadowline",
    label: "See Live",
  },
  {
    name: "Site of the day",
    type: "Awwwards",
    project: "Verse 21",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "LVXH - AMOT",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Open Field Audio",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "ArtisanCraft",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Disguised Edge",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "Silvia Santiago",
    label: "See Live",
  },
  {
    name: "Developer Award",
    type: "Awwwards",
    project: "2023 Showcase",
    label: "See Live",
  },
];
